pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'HorseStatsVanilla'
includeBuild('build-logic')
include('common')
include('fabric')
include('neoforge')
